// frameworks/solid-app/src/routes/index.tsx
import { useRouteData, useSearchParams } from "solid-start";
import { createServerAction$, createServerData$ } from "solid-start/server";
import { TodoItem } from "~/components/TodoItem";
import { createTodo, getTodos } from "~/components/actions";

export function routeData() {
  return createServerData$(async () => {
    const [searchParams] = useSearchParams();

    const todoBenchmark =
      typeof searchParams.todoBenchmark === "string" &&
      !Number.isNaN(Number(searchParams.todoBenchmark))
        ? Number(searchParams.todoBenchmark)
        : undefined;

    const todos = await getTodos();

    return { todos, todoBenchmark };
  });
}

export default function Home() {
  const { latest } = useRouteData<typeof routeData>();

  const [enrolling, { Form }] = createServerAction$(async (form: FormData) => {
    createTodo(form);
  });

  return (
    <main>
      <Form>
        <input type="text" name="name" id="name" />
        <button type="submit" disabled={enrolling.pending}>
          Create
        </button>
      </Form>
      <ul>
        {latest?.todoBenchmark && latest?.todos
          ? Array(latest.todoBenchmark)
              .fill(latest.todos[1])
              .map((todo) => <TodoItem todo={todo} />)
          : latest?.todos.map((todo) => <TodoItem todo={todo} />)}
      </ul>
    </main>
  );
}

// frameworks/svelte-app/src/routes/+page.svelte
<script lang="ts">
  import { enhance } from "$app/forms";

  import { page } from "$app/stores";
  import TodoItem from "./TodoItem.svelte";

  export let data;
  $: todos = data.todos;

  const todoBenchmark =
    $page.url.searchParams.has("todoBenchmark") &&
    !isNaN(Number($page.url.searchParams.get("todoBenchmark")))
      ? Number($page.url.searchParams.get("todoBenchmark"))
      : undefined;
</script>

<form method="post" action="?/createTodo" use:enhance>
  <input type="text" name="name" id="name" />
  <button type="submit">Create</button>
</form>
<ul>
  {#if todoBenchmark}
    {#each Array(todoBenchmark).fill(todos[1]) as todo}
      <TodoItem {todo} />
    {/each}
  {:else}
    {#each todos as todo}
      <TodoItem {todo} />
    {/each}
  {/if}
</ul>
